### Register
POST http://localhost:3080/auth/register
Content-Type: application/json

{
  "name": "",
  "email": "",
  "password": ""
}


###Login
POST http://localhost:3080/auth/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}